# Generated by Django 3.1.7 on 2021-04-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('state', models.IntegerField(default=1)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'kind',
                'verbose_name_plural': 'kind',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=512)),
                ('img', models.CharField(max_length=512)),
                ('desc', models.CharField(max_length=256)),
                ('recommend', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=1)),
                ('sort', models.IntegerField(default=0)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.kind')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tools')),
            ],
            options={
                'verbose_name': 'navigation',
                'verbose_name_plural': 'navigation',
            },
        ),
    ]
